name: dayfi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  google_ml_kit: 
  ml_card_scanner: ^0.2.1
  supabase_flutter: ^2.8.3
  get_storage: ^2.1.1
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.1
  loading_indicator: ^3.1.1
  lottie: ^3.3.1
  # credit_card_scanner: ^1.0.5

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-VariableFont_wght.ttf

    - family: Karla
      fonts:
        - asset: assets/fonts/karla/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/karla/Karla-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/karla/Karla-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/karla/Karla-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/karla/Karla-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/karla/Karla-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/karla/Karla-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/karla/Karla-Light.ttf
          weight: 300
        - asset: assets/fonts/karla/Karla-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/karla/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/karla/Karla-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/karla/Karla-Regular.ttf
          weight: 400
        - asset: assets/fonts/karla/Karla-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/karla/Karla-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: DegularDisplay
      fonts:
        - asset: assets/fonts/DegularDisplay-Black.otf
        - asset: assets/fonts/DegularDisplay-BlackItalic.otf
        - asset: assets/fonts/DegularDisplay-Bold.otf
        - asset: assets/fonts/DegularDisplay-BoldItalic.otf
        - asset: assets/fonts/DegularDisplay-Light.otf
        - asset: assets/fonts/DegularDisplay-LightItalic.otf
        - asset: assets/fonts/DegularDisplay-Medium.otf
        - asset: assets/fonts/DegularDisplay-MediumItalic.otf
        - asset: assets/fonts/DegularDisplay-Regular.otf
        - asset: assets/fonts/DegularDisplay-RegularItalic.otf
        - asset: assets/fonts/DegularDisplay-Semibold.otf
        - asset: assets/fonts/DegularDisplay-SemiboldItalic.otf
        - asset: assets/fonts/DegularDisplay-Thin.otf
        - asset: assets/fonts/DegularDisplay-ThinItalic.otf
